# Site settings
title: '小猫杯' # Your Title
tagline: 'Where there is a will, there is a way' # A brief tagline for your site

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: '' # the subpath of your site, e.g. /blog/
